"use strict";var QWebChannelMessageTypes={signal:1,propertyUpdate:2,init:3,idle:4,debug:5,invokeMethod:6,connectToSignal:7,disconnectFromSignal:8,setProperty:9,response:10};var QWebChannel=function(transport,initCallback){if(typeof transport==="undefined"){console.error("WebChannel transport is undefined!");return;}
var channel=this;this.transport=transport;this.send=function(data){if(typeof data!=="string"){data=JSON.stringify(data);}
channel.transport.send(data);};this.onmessage=function(message){var data=message.data;if(typeof data==="string"){data=JSON.parse(data);}
switch(data.type){case QWebChannelMessageTypes.signal:channel.handleSignal(data);break;case QWebChannelMessageTypes.response:channel.handleResponse(data);break;case QWebChannelMessageTypes.propertyUpdate:channel.handlePropertyUpdate(data);break;default:console.error("invalid message received:",message.data);}};transport.onmessage=this.onmessage;this.execCallbacks={};this.execId=0;this.exec=function(data,callback){if(!callback){channel.send(data);return;}
if(channel.execId===Number.MAX_VALUE){channel.execId=Number.MIN_VALUE;}
if(data.hasOwnProperty("id")){console.error("Cannot exec message with property id: "+JSON.stringify(data));return;}
data.id=channel.execId++;channel.execCallbacks[data.id]=callback;channel.send(data);};this.objects={};this.handleSignal=function(message){var object=channel.objects[message.object];if(object){object.signalEmitted(message.signal,message.args);}else{console.warn("Unhandled signal: "+message.object+"::"+message.signal);}};this.handleResponse=function(message){if(!message.hasOwnProperty("id")){console.error("Invalid response message received: ",JSON.stringify(message));return;}
channel.execCallbacks[message.id](message.data);delete channel.execCallbacks[message.id];};this.handlePropertyUpdate=function(message){var object=channel.objects[message.object];if(object){object.propertyUpdate(message.signals,message.properties);}else{console.warn("Unhandled property update: "+message.object+"::"+message.signal);}};this.debug=function(message){channel.send({type:QWebChannelMessageTypes.debug,data:message});};channel.exec({type:QWebChannelMessageTypes.init},function(data){for(var objectName in data){var object=new QObject(objectName,data[objectName],channel);}
if(initCallback){initCallback(channel);}
channel.exec({type:QWebChannelMessageTypes.idle});});};var QObject=function(name,data,webChannel){this.__id__=name;webChannel.objects[name]=this;var object=this;this.unwrapQObject=function(response){if(response instanceof Array){return response.map(function(qobj){return object.unwrapQObject(qobj);});}
if(!(response instanceof Object)){return response;}
if(!response["__QObject*__"]||response.id===undefined){var jObj={};for(var propName in response){var propValue=response[propName];if(propValue instanceof Object&&propValue["__QObject*__"]!==undefined&&propValue.id!==undefined){propValue=object.unwrapQObject(propValue);}
jObj[propName]=propValue;}
return jObj;}
if(webChannel.objects[response.id]!==undefined){return webChannel.objects[response.id];}
var objectInfo=response;var qObject=new QObject(objectInfo.id,objectInfo,webChannel);qObject.destroyed.connect(function(){if(webChannel.objects[response.id]===qObject){delete webChannel.objects[response.id];}});return qObject;};this.unwrapProperties=function(){for(var propertyIdx in object.__propertyCache__){var property=object.__propertyCache__[propertyIdx];if(property instanceof Object&&property["__QObject*__"]!==undefined&&property.id!==undefined){object.__propertyCache__[propertyIdx]=object.unwrapQObject(property);}}};function addMethod(methodData){object[methodData[0]]=function(){var args=[];var callback;for(var i=0;i<arguments.length;++i){if(typeof arguments[i]==="function")callback=arguments[i];else args.push(arguments[i]);}
webChannel.exec({type:QWebChannelMessageTypes.invokeMethod,object:object.__id__,method:methodData[1],args:args},function(response){if(response!==undefined){var result=object.unwrapQObject(response);if(callback){callback(result);}}});};}
function bindGetterSetter(propertyInfo){var propertyIndex=propertyInfo[0];var propertyName=propertyInfo[1];var notifySignalData=propertyInfo[2];if(notifySignalData){if(notifySignalData[0]===1){object.signalEmitted(notifySignalData[1],notifySignalData[2]);}else{object.connectNotifySignal(notifySignalData[0],notifySignalData[1]);}}
Object.defineProperty(object,propertyName,{configurable:true,get:function(){var propertyValue=object.__propertyCache__[propertyIndex];if(propertyValue===undefined){console.warn("Undefined value in property cache for property \""+propertyName+"\" in object "+object.__id__);}
return propertyValue;},set:function(value){if(value===undefined){console.warn("Property setter for "+propertyName+" called with undefined value!");}
object.__propertyCache__[propertyIndex]=value;webChannel.exec({type:QWebChannelMessageTypes.setProperty,object:object.__id__,property:propertyIndex,value:value});}});}
this.__propertyCache__={};var self=this;function addSignal(signalData,isPropertyNotifySignal){var signalName=signalData[0];var signalIndex=signalData[1];object[signalName]={connect:function(callback){if(typeof callback!=="function"){console.error("Bad callback given to connect to signal "+signalName);return;}
object.__objectSignals__[signalIndex]=object.__objectSignals__[signalIndex]||[];object.__objectSignals__[signalIndex].push(callback);if(!isPropertyNotifySignal&&signalName!=="destroyed"){webChannel.exec({type:QWebChannelMessageTypes.connectToSignal,object:object.__id__,signal:signalIndex});}},disconnect:function(callback){if(typeof callback!=="function"){console.error("Bad callback given to disconnect from signal "+signalName);return;}
object.__objectSignals__[signalIndex]=object.__objectSignals__[signalIndex]||[];var idx=object.__objectSignals__[signalIndex].indexOf(callback);if(idx===-1){console.error("Cannot find connection of signal "+signalName+" to "+callback.name);return;}
object.__objectSignals__[signalIndex].splice(idx,1);if(!isPropertyNotifySignal&&object.__objectSignals__[signalIndex].length===0){webChannel.exec({type:QWebChannelMessageTypes.disconnectFromSignal,object:object.__id__,signal:signalIndex});}}}}
this.__objectSignals__={};this.signalEmitted=function(signalIndex,signalArgs){var connections=object.__objectSignals__[signalIndex];if(connections){connections.forEach(function(callback){callback.apply(callback,object.unwrapQObject(signalArgs));});}};this.propertyUpdate=function(signals,propertyMap){for(var propertyIndex in propertyMap){var propertyValue=propertyMap[propertyIndex];object.__propertyCache__[propertyIndex]=propertyValue;}
for(var signalIndex in signals){object.signalEmitted(signalIndex,signals[signalIndex]);}};this.connectNotifySignal=function(signalIndex,propertyIndex){if(object.__id__.length){webChannel.exec({type:QWebChannelMessageTypes.connectToSignal,object:object.__id__,signal:signalIndex});}};for(var i in data.methods){addMethod(data.methods[i]);}
for(var i in data.properties){bindGetterSetter(data.properties[i]);}
for(var i in data.signals){addSignal(data.signals[i],false);}
for(var i in data.enums){object[i]=data.enums[i];}};
